---
- name: display facts
  hosts: all
  gather_facts: false
  tasks:
   - name: debug OS
     debug:
       msg: "{{ item }}"
     loop:
        - "OS: {{ ansible_facts['distribution'] }}"
        - "RAM: {{ ansible_facts['memtotal_mb'] }}"
        - "BIOS Version: {{ ansible_facts['bios_version'] }}"
