---
- name: creating webserver content using a jinja2
  hosts: all
  tasks:
   - name: deploy index.html.j2 to /var/www/html/index.html
     template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: root
      group: root
