---
- name: update index.html file
  hosts: all
  become: true
  tasks:
   - name: updating index.html with new content
     copy:
      content: "hello world\n"
      dest: /var/www/html/index.html
     register: httpd_output
     failed_when: '"Hello World" not in httpd_output.content'
