---
- name: manipulating service state
  hosts: all
  become: true
  tasks:
   - name: ensure {{ svc_name }} is stopped
     service:
      name: "{{ svc_name }}"
      state: stopped

   - name: create user and assign password
     user:
      name: "{{ user_name }}"
      password: "{{ user_pass | password_hash('sha512') }}"
      state: present
